### ISSUE TITLE
Bug in cast to Structure2D

### ISSUE THREAD

**Issue by cupertank** [mipt-npm/kmath#82] opened 2020-04-03 13:28 UTC
There is a probable bug in cast of NDStructure to Structure2D with as2D() function. In that case class uses swapped rowNum and colNum values because of the reversed shape, so in fact you store row number in colNum and vice versa. 
https://github.com/mipt-npm/kmath/blob/e52cfcaafe7eb1149170838d9910e54851ba1a92/kmath-core/src/commonMain/kotlin/scientifik/kmath/structures/Structure2D.kt#L7-L8
Since rowNum and colNum values are swapped, there is also another probable bug in get method (swapped requested column and row indices again)
https://github.com/mipt-npm/kmath/blob/e52cfcaafe7eb1149170838d9910e54851ba1a92/kmath-core/src/commonMain/kotlin/scientifik/kmath/structures/Structure2D.kt#L18-L20
For example, this makes dot operation for the structures work incorrectly.
A simple example that shows an error: 
```
val firstMatrix = BufferNDStructure(DefaultStrides(intArrayOf(3, 2)), ListBuffer(6) { 1.0 })
val secondMatrix = BufferNDStructure(DefaultStrides(intArrayOf(5, 3)), ListBuffer(15) { 1.0 })
val product = MatrixContext.real.run { firstMatrix.as2D() dot secondMatrix.as2D() }
```
My possible fix - [link](https://github.com/cupertank/kmath/commit/ef2ec4f8718d5e89c574c5000db7e82d1222f960)

**Comment by altavir** [comment] 2020-04-03 14:21
Thanks for the report. 

Just at a glance I do not understand where the problem is. By default we are assuming that first index Is the row index and the second index is the column index, so in the shape number of rows should go first.

I will need to check it and then I will get back to you.

**Comment by altavir** [comment] 2020-04-03 14:40
@cupertank It seems like the problem in your example, not in the code. You are taking matrix with 3 rows and 2 columns and trying to multiply it by matrix with 5 rows and 3 columns. It won't work. 

By the way, there is easier way to generate matrices:
```kotlin
        val firstMatrix = NDStructure.auto(2, 3) { 1.0 }
        val secondMatrix = NDStructure.auto(3, 5) { 1.0 }

        MatrixContext.real.run {
            firstMatrix.as2D() dot secondMatrix.as2D()
        }
```

also you can load `kmath-for-real` module, which have a number of extensions for work with real numbers and just use `realMatrix` builder.

**Comment by altavir** [comment] 2020-04-03 14:44
Even nicer test syntax:
```kotlin
        MatrixContext.real.run{
            val firstMatrix = produce(2,3){ _,_ -> 1.0}
            val secondMatrix = produce(3,5){ _,_ -> 2.0}
            val result =  firstMatrix.as2D() dot secondMatrix.as2D()
            assertEquals(2, result.rowNum)
            assertEquals(5, result.colNum)
        }
```

**Comment by cupertank** [comment] 2020-04-03 14:53
If you look at your DefaultStrides, you will see that shape should be cast as [colNum, rowNum].
https://github.com/mipt-npm/kmath/blob/e52cfcaafe7eb1149170838d9910e54851ba1a92/kmath-core/src/commonMain/kotlin/scientifik/kmath/structures/NDStructure.kt#L117-L139

In our project, we work mainly with tensors, and not with matrices, so we do not use such a creation of matrices.

**Comment by altavir** [comment] 2020-04-03 15:03
Strides inner implementation should not be exposed. I had some difficulties with figuring out, how do do them properly. The issue is still there:  #23. In your example, you explicitly use dimensions to construct strides, so it should provide correct rows-first, columns-second order. Conversion to 2d is working as expected. If there is a error, it should be in strides generation. For now all my test run green. I will add another one just to be sure.

**Comment by altavir** [comment] 2020-04-03 15:22
I found out that `BufferMatrix` is optimized not to use strides at all, but I've modified example to use strided implementation:
```kotlin
        val firstMatrix = NDStructure.auto(2,3){ (i, j) -> (i + j).toDouble() }.as2D()
        val secondMatrix = NDStructure.auto(3,2){ (i, j) -> (i + j).toDouble() }.as2D()
        MatrixContext.real.run {
//            val firstMatrix = produce(2, 3) { i, j -> (i + j).toDouble() }
//            val secondMatrix = produce(3, 2) { i, j -> (i + j).toDouble() }
            val result = firstMatrix dot secondMatrix
            assertEquals(2, result.rowNum)
            assertEquals(2, result.colNum)
            assertEquals(8.0, result[0,1])
            assertEquals(8.0, result[1,0])
            assertEquals(14.0, result[1,1])
        }
```

It still gives correct results. I am not sure about the correct order of elements in the buffer, it could be inverted. It would be nice if you could contribute #23 to allow different types of strides.

**Comment by cupertank** [comment] 2020-04-03 18:05
Okay, how do I make a matrix of this kind from the buffer [0, 1, 2, 3, 4, 5]?
![MSP151814629447c648ig3000002ab51bga94c38030](https://user-images.githubusercontent.com/34806644/78391314-cd954700-75ee-11ea-839f-c75a09e0052a.gif)

**Comment by cupertank** [comment] 2020-04-03 18:08
Such a solution creates such a matrix
`val matrix = BufferNDStructure(DefaultStrides(intArrayOf(2, 3)), ListBuffer(6) { it })`
![MSP30651g0ich3353h8ggb400005fh4fe520eehh770](https://user-images.githubusercontent.com/34806644/78391512-341a6500-75ef-11ea-9d9e-454b6fac1c6f.gif)

**Comment by altavir** [comment] 2020-04-03 18:54
Matrix builders was introduced exactly for that reason: https://github.com/mipt-npm/kmath/blob/e52cfcaafe7eb1149170838d9910e54851ba1a92/kmath-core/src/commonTest/kotlin/scientifik/kmath/linear/MatrixTest.kt#L47-L54. It is not optimized for performance and should be used only for small matrices, but I think it should do the trick. If you have something else in mind, please open a new issue and I will add it right away. Strides are not meant to be used directly save for cases, when you need to work with external structures.

**Comment by altavir** [comment] 2020-04-11 11:18
Closing it for now. Please open new issues if you want to have some kind of change in behavior.

**Closed by altavir** 2020-04-11 11:18 UTC
Labels: bug
